### ISSUE TITLE
Run with panic error

### ISSUE THREAD

**Issue by ringsaturn** [hugopendlebury/polars-dates#1]
Hi there,

I notice this repo from https://github.com/ringsaturn/tzf-rs/network/dependents and thank you for making such a extension that I want to build for a while for tzf-rs.

I'm trying to add it to my repo https://github.com/ringsaturn/df-lng-lat-timezones

However I run the sample codes with errors:

```py
import polars as pl
import polars_dates as pl_dates
from datetime import datetime

df = pl.DataFrame(
    data={
        "lat": [51.5054, 51.5054, 40.7128, 40.7128, 40.7128],
        "lon": [0.0235, 0.0235, -74.0060, -74.0060, -74.0060],
        "dt": [
            datetime(2024, 1, 24, 9, 0, 0),
            datetime(2024, 1, 24, 9, 0, 0),
            datetime(2024, 1, 24, 9, 0, 0),
            datetime(2024, 1, 24, 3, 0, 0),
            datetime(2024, 1, 24, 3, 0, 0),
        ],
        "values": [5, 5, 5, 10, 10],
    }
).with_columns(pl_dates.lookup_timezone(pl.col("lat"), pl.col("lon")))
```

```bash
RUST_BACKTRACE=full python3 sample.py
```

```console
thread '<unnamed>' panicked at crates/polars-plan/src/dsl/function_expr/plugin.rs:28:18:
called `Result::unwrap()` on an `Err` value: DlSym { desc: "dlsym(0x8c8044c0, _polars_plugin_get_version): symbol not found" }
stack backtrace:
   0:        0x108d310b8 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h25ab8285f33782dc
   1:        0x106fb5880 - core::fmt::write::h15efff1d4a94cc73
   2:        0x108d09a04 - std::io::Write::write_fmt::hb30c6e8d074ee653
   3:        0x108d32830 - std::sys_common::backtrace::print::hb92bc5fab2216803
   4:        0x108d32118 - std::panicking::default_hook::{{closure}}::h3632b5786ed283e9
   5:        0x108d33028 - std::panicking::rust_panic_with_hook::hf1921838e4b40ae2
   6:        0x108d32b78 - std::panicking::begin_panic_handler::{{closure}}::ha4140b690c71fc3c
   7:        0x108d32adc - std::sys_common::backtrace::__rust_end_short_backtrace::h7eab3206bb3f96a1
   8:        0x108d32ad0 - _rust_begin_unwind
   9:        0x108ede0ac - core::panicking::panic_fmt::h92c6841e0ee43d69
  10:        0x108ede460 - core::result::unwrap_failed::h40d5e533400b601b
  11:        0x108782d48 - polars_plan::dsl::function_expr::plugin::get_lib::hd0a718ae1ef2ee99
  12:        0x10878109c - polars_plan::dsl::function_expr::plugin::plugin_field::h82e42eeba0170b48
  13:        0x1087799e0 - polars_plan::logical_plan::aexpr::schema::<impl polars_plan::logical_plan::aexpr::AExpr>::to_field::h7c50fe1136e33371
  14:        0x108956e2c - polars_plan::utils::expressions_to_schema::he94a39e792396da5
  15:        0x1089557ec - polars_plan::logical_plan::builder::prepare_projection::ha3f97ccd2b94dd66
  16:        0x108961528 - polars_plan::logical_plan::builder::LogicalPlanBuilder::with_columns::hac1f7f959165568d
  17:        0x106e29db4 - polars::lazyframe::_::<impl polars::lazyframe::PyLazyFrame>::__pymethod_with_columns__::h37d559abe9c36628
  18:        0x10688c928 - pyo3::impl_::trampoline::trampoline::h303f836ea3e9e5ef
  19:        0x106ed6dd4 - polars::lazyframe::_::_::__INVENTORY::trampoline::hb6104f678ec5e8b0
  20:        0x1016ac420 - _method_vectorcall_VARARGS_KEYWORDS
  21:        0x1016a0f88 - _PyObject_Vectorcall
  22:        0x101780dcc - __PyEval_EvalFrameDefault
  23:        0x101778918 - __PyEval_Vector
  24:        0x1016a3678 - _method_vectorcall
  25:        0x1017828e0 - __PyEval_EvalFrameDefault
  26:        0x1017787e8 - _PyEval_EvalCode
  27:        0x1017cb6a0 - _run_mod
  28:        0x1017c9b94 - __PyRun_SimpleFileObject
  29:        0x1017c961c - __PyRun_AnyFileObject
  30:        0x1017e8d4c - _Py_RunMain
  31:        0x1017e90fc - _pymain_main
  32:        0x1017e919c - _Py_BytesMain
Traceback (most recent call last):
  File "/Users/ringsaturn/Projects/df-lng-lat-timezones/deps/polars-dates/sample.py", line 18, in <module>
    ).with_columns(pl_dates.lookup_timezone(pl.col("lat"), pl.col("lon")))
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ringsaturn/Projects/df-lng-lat-timezones/venv/lib/python3.11/site-packages/polars/dataframe/frame.py", line 8276, in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ringsaturn/Projects/df-lng-lat-timezones/venv/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 4000, in with_columns
    return self._from_pyldf(self._ldf.with_columns(pyexprs))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: DlSym { desc: "dlsym(0x8c8044c0, _polars_plugin_get_version): symbol not found" }
```

I build it from commit 9a1c10d9177dd015cf4eb70634045e47f2ad9eb5

**Comment by hugopendlebury** [comment]
Hi.

Wow you move fast. I've just started working on this. However I'm aware of the behaviour you have seen and don't believe it's specific to this project / code. Last year I wrote a few polars functions related to validation which also showed the DlSym issue when I last tried to run it (after not touching the code for months)

I think it's due to polars being fussy and fast moving and deprecating API / moving things around. 

Which version of polars are you trying to use ? Main has been built against polars==0.20.2

You will also a branch called polars 19_12 which is built to target version 0.19.12.

Perhaps create a VENV and install one of these versions and see how you get on ?

My use case is I'm working with a binary format of weather data in a format called grib. These files basically split the globe into lots of small grids which contain parameters around weather forecasts. Since each message can be spread over the globe it also provides lat / long details. I want to be able to create aggregations such as mean but using the local times / dates rather than the UTC value supplied. Hence using this library to contain the time zone and then using chrono to obtain the time in that location. Sadly parquet and arrow do not support storing multiple timezones in a single column but I think what I currently there should be sufficient to get something working and provide accurate calculations.

I also meant to ask. When multiple timezones are detected, is the last value always the most accurate / local. E.g. in the case of China on the Western side the first value appears to be +8 hrs and the last +6 which is most accurate for the region.

**Comment by ringsaturn** [comment]
Thanks, I reinstall from main branch after lock polars version as 0.20.2 and it works fine.

But I have to add these comments to run, since there is an import problem

```diff
(venv) ➜  polars-dates git:(main) ✗ git diff | cat                     
diff --git a/polars_dates/__init__.py b/polars_dates/__init__.py
index 83ecc8f..7d6e3d9 100644
--- a/polars_dates/__init__.py
+++ b/polars_dates/__init__.py
@@ -4,7 +4,7 @@ import polars_dates.namespace  # noqa: F401
 from polars_dates.functions import (
     echo,
     lookup_timezone,
-    to_timezone_aware_date
+    # to_timezone_aware_date
 )
 
 from ._internal import __version__
@@ -12,6 +12,6 @@ from ._internal import __version__
 __all__ = [
     "echo",
     "lookup_timezone",
-    "to_timezone_aware_date"
+    # "to_timezone_aware_date"
     "__version__",
 ]
```

**Comment by hugopendlebury** [comment]
Good to hear it's working for you. I think I renamed that function.

Basically I got it working initially on 0.20.2 but then realised at work we are using 0.19.12 and unlikely to upgrade for a while, so created a branch and made the necessary changes to get something running on 0.19.12 - neglecting to go back to master and check everything was fine.

If you rename the function in __init__ to to_local_in_new_timezone then you should be able to get localised dates.

Will update main later. The samples / read me it probably also out of sync
